export const phoneCodes = [
  { code: "Australia", name: "+61", value: "AU" },
  { code: "Canada", name: "+1", value: "CA" },
  { code: "France", name: "+33", value: "FR" },
  { code: "Germany", name: "+49", value: "DE" },
  { code: "Ireland", name: "+353", value: "IE" },
  { code: "Italy", name: "+39", value: "IT" },
  { code: "Netherlands", name: "+31", value: "NL" },
  { code: "New Zealand", name: "+64", value: "NZ" },
  { code: "United Kingdom", name: "+44", value: "GB" },
  { code: "United States of America", name: "+1", value: "US" },
  { code: "Afghanistan", name: "+93", value: "AF" },
  { code: "Aland Islands", name: "+358", value: "AX" },
  { code: "Albania", name: "+355", value: "AL" },
  { code: "Algeria", name: "+213", value: "DZ" },
  { code: "American Samoa", name: "+1-684", value: "AS" },
  { code: "Andorra", name: "+376", value: "AD" },
  { code: "Angola", name: "+244", value: "AO" },
  { code: "Anguilla", name: "+1-264", value: "AI" },
  { code: "Antarctica", name: "+672", value: "AQ" },
  { code: "Antigua and Barbuda", name: "+1-268", value: "AG" },
  { code: "Argentina", name: "+54", value: "AR" },
  { code: "Armenia", name: "+374", value: "AM" },
  { code: "Aruba", name: "+297", value: "AW" },
  { code: "Australia", name: "+61", value: "AU" },
  { code: "Austria", name: "+43", value: "AT" },
  { code: "Azerbaijan", name: "+994", value: "AZ" },
  { code: "Bahamas", name: "+1-242", value: "BS" },
  { code: "Bahrain", name: "+973", value: "BH" },
  { code: "Bangladesh", name: "+880", value: "BD" },
  { code: "Barbados", name: "+1-246", value: "BB" },
  { code: "Belarus", name: "+375", value: "BY" },
  { code: "Belgium", name: "+32", value: "BE" },
  { code: "Belize", name: "+501", value: "BZ" },
  { code: "Benin", name: "+229", value: "BJ" },
  { code: "Bermuda", name: "+1-441", value: "BM" },
  { code: "Bhutan", name: "+975", value: "BT" },
  { code: "Bolivia", name: "+591", value: "BO" },
  { code: "Bonaire", name: "+599", value: "BQ" },
  { code: "Bosnia and Herzegovina", name: "+387", value: "BA" },
  { code: "Botswana", name: "+267", value: "BW" },
  { code: "Bouvet Island", name: "+55", value: "BV" },
  { code: "Brazil", name: "+55", value: "BR" },
  { code: "British Indian Ocean Territory", name: "+246", value: "IO" },
  { code: "Brunei Darussalam", name: "+673", value: "BN" },
  { code: "Bulgaria", name: "+359", value: "BG" },
  { code: "Burkina Faso", name: "+226", value: "BF" },
  { code: "Burundi", name: "+257", value: "BI" },
  { code: "Cabo Verde", name: "+238", value: "CV" },
  { code: "Cambodia", name: "+855", value: "KH" },
  { code: "Cameroon", name: "+237", value: "CM" },
  { code: "Canada", name: "+1", value: "CA" },
  { code: "Cayman Islands", name: "+1-345", value: "KY" },
  { code: "Central African Republic", name: "+236", value: "CF" },
  { code: "Chad", name: "+235", value: "TD" },
  { code: "Chile", name: "+56", value: "CL" },
  { code: "China", name: "+86", value: "CN" },
  { code: "Christmas Island", name: "+61", value: "CX" },
  { code: "Cocos (Keeling) Islands", name: "+61", value: "CC" },
  { code: "Colombia", name: "+57", value: "CO" },
  { code: "Comoros", name: "+269", value: "KM" },
  { code: "Cook Islands", name: "+682", value: "CK" },
  { code: "Costa Rica", name: "+506", value: "CR" },
  { code: "Cote d'Ivoire", name: "+225", value: "CI" },
  { code: "Croatia", name: "+385", value: "HR" },
  { code: "Curacao", name: "+599", value: "CW" },
  { code: "Cyprus", name: "+357", value: "CY" },
  { code: "Czechia", name: "+420", value: "CZ" },
  { code: "Denmark", name: "+45", value: "DK" },
  { code: "Djibouti", name: "+253", value: "DJ" },
  { code: "Dominica", name: "+1-767", value: "DM" },
  { code: "Dominican Republic", name: "+1-809", value: "DO" },
  { code: "Ecuador", name: "+593", value: "EC" },
  { code: "Egypt", name: "+20", value: "EG" },
  { code: "El Salvador", name: "+503", value: "SV" },
  { code: "Equatorial Guinea", name: "+240", value: "GQ" },
  { code: "Eritrea", name: "+291", value: "ER" },
  { code: "Estonia", name: "+372", value: "EE" },
  { code: "Ethiopia", name: "+251", value: "ET" },
  { code: "Falkland Islands", name: "+500", value: "FK" },
  { code: "Faroe Islands", name: "+298", value: "FO" },
  { code: "Fiji", name: "+679", value: "FJ" },
  { code: "Finland", name: "+358", value: "FI" },
  { code: "France", name: "+33", value: "FR" },
  { code: "French Guiana", name: "+594", value: "GF" },
  { code: "French Polynesia", name: "+689", value: "PF" },
  { code: "French Southern Territories and Antarctic Lands", name: "+262", value: "TF" },
  { code: "Gabon", name: "+241", value: "GA" },
  { code: "Gambia", name: "+220", value: "GM" },
  { code: "Georgia", name: "+995", value: "GE" },
  { code: "Germany", name: "+49", value: "DE" },
  { code: "Ghana", name: "+233", value: "GH" },
  { code: "Gibraltar", name: "+350", value: "GI" },
  { code: "Greece", name: "+30", value: "GR" },
  { code: "Greenland", name: "+299", value: "GL" },
  { code: "Grenada", name: "+1-473", value: "GD" },
  { code: "Guadeloupe", name: "+590", value: "GP" },
  { code: "Guam", name: "+1-671", value: "GU" },
  { code: "Guatemala", name: "+502", value: "GT" },
  { code: "Guernsey", name: "+44-1481", value: "GG" },
  { code: "Guinea", name: "+224", value: "GN" },
  { code: "Guinea-Bissau", name: "+245", value: "GW" },
  { code: "Guyana", name: "+592", value: "GY" },
  { code: "Haiti", name: "+509", value: "HT" },
  { code: "Heard Island and McDonald Islands", name: "+61", value: "HM" },
  { code: "Holy See (Vatican City State)", name: "+379", value: "VA" },
  { code: "Honduras", name: "+504", value: "HN" },
  { code: "Hong Kong", name: "+852", value: "HK" },
  { code: "Hungary", name: "+36", value: "HU" },
  { code: "Iceland", name: "+354", value: "IS" },
  { code: "India", name: "+91", value: "IN" },
  { code: "Indonesia", name: "+62", value: "ID" },
  { code: "Ireland", name: "+353", value: "IE" },
  { code: "Isle of Man", name: "+44-1624", value: "IM" },
  { code: "Israel", name: "+972", value: "IL" },
  { code: "Italy", name: "+39", value: "IT" },
  { code: "Jamaica", name: "+1-876", value: "JM" },
  { code: "Japan", name: "+81", value: "JP" },
  { code: "Jersey", name: "+44-1534", value: "JE" },
  { code: "Jordan", name: "+962", value: "JO" },
  { code: "Kazakhstan", name: "+7", value: "KZ" },
  { code: "Kenya", name: "+254", value: "KE" },
  { code: "Kiribati", name: "+686", value: "KI" },
  { code: "Kuwait", name: "+965", value: "KW" },
  { code: "Kyrgyzstan", name: "+996", value: "KG" },
  { code: "Lao People's Democratic Republic", name: "+856", value: "LA" },
  { code: "Latvia", name: "+371", value: "LV" },
  { code: "Lebanon", name: "+961", value: "LB" },
  { code: "Lesotho", name: "+266", value: "LS" },
  { code: "Liberia", name: "+231", value: "LR" },
  { code: "Libya", name: "+218", value: "LY" },
  { code: "Liechtenstein", name: "+423", value: "LI" },
  { code: "Lithuania", name: "+370", value: "LT" },
  { code: "Luxembourg", name: "+352", value: "LU" },
  { code: "Macao", name: "+853", value: "MO" },
  { code: "Macedonia", name: "+389", value: "MK" },
  { code: "Madagascar", name: "+261", value: "MG" },
  { code: "Malawi", name: "+265", value: "MW" },
  { code: "Malaysia", name: "+60", value: "MY" },
  { code: "Maldives", name: "+960", value: "MV" },
  { code: "Mali", name: "+223", value: "ML" },
  { code: "Malta", name: "+356", value: "MT" },
  { code: "Martinique", name: "+596", value: "MQ" },
  { code: "Mauritania", name: "+222", value: "MR" },
  { code: "Mauritius", name: "+230", value: "MU" },
  { code: "Mayotte", name: "+269", value: "YT" },
  { code: "Mexico", name: "+52", value: "MX" },
  { code: "Micronesia", name: "+691", value: "FM" },
  { code: "Moldova", name: "+373", value: "MD" },
  { code: "Monaco", name: "+377", value: "MC" },
  { code: "Mongolia", name: "+976", value: "MN" },
  { code: "Montenegro", name: "+382", value: "ME" },
  { code: "Montserrat", name: "+1-664", value: "MS" },
  { code: "Morocco", name: "+212", value: "MA" },
  { code: "Mozambique", name: "+258", value: "MZ" },
  { code: "Myanmar", name: "+95", value: "MM" },
  { code: "Namibia", name: "+264", value: "NA" },
  { code: "Nauru", name: "+674", value: "NR" },
  { code: "Nepal", name: "+977", value: "NP" },
  { code: "Netherlands", name: "+31", value: "NL" },
  { code: "Netherlands Antilles", name: "+599", value: "AN" },
  { code: "New Caledonia", name: "+687", value: "NC" },
  { code: "New Zealand", name: "+64", value: "NZ" },
  { code: "Nicaragua", name: "+505", value: "NI" },
  { code: "Niger", name: "+227", value: "NE" },
  { code: "Nigeria", name: "+234", value: "NG" },
  { code: "Niue", name: "+683", value: "NU" },
  { code: "Norfolk Island", name: "+672", value: "NF" },
  { code: "Northern Mariana Islands", name: "+1-670", value: "MP" },
  { code: "Norway", name: "+47", value: "NO" },
  { code: "Oman", name: "+968", value: "OM" },
  { code: "Pakistan", name: "+92", value: "PK" },
  { code: "Palau", name: "+680", value: "PW" },
  { code: "Palestine, State of", name: "+970", value: "PS" },
  { code: "Panama", name: "+507", value: "PA" },
  { code: "Papua New Guinea", name: "+675", value: "PG" },
  { code: "Paraguay", name: "+595", value: "PY" },
  { code: "Peru", name: "+51", value: "PE" },
  { code: "Philippines", name: "+63", value: "PH" },
  { code: "Pitcairn", name: "+64", value: "PN" },
  { code: "Poland", name: "+48", value: "PL" },
  { code: "Portugal", name: "+351", value: "PT" },
  { code: "Puerto Rico", name: "+1", value: "PR" },
  { code: "Qatar", name: "+974", value: "QA" },
  { code: "Reunion", name: "+262", value: "RE" },
  { code: "Romania", name: "+40", value: "RO" },
  { code: "Russian Federation", name: "+7", value: "RU" },
  { code: "Rwanda", name: "+250", value: "RW" },
  { code: "Saint Helena", name: "+290", value: "SH" },
  { code: "Saint Kitts and Nevis", name: "+1-869", value: "KN" },
  { code: "Saint Lucia", name: "+1-758", value: "LC" },
  { code: "Saint Martin", name: "+590", value: "MF" },
  { code: "Saint Pierre and Miquelon", name: "+508", value: "PM" },
  { code: "Saint Vincent and the Grenadines", name: "+1-784", value: "VC" },
  { code: "Samoa", name: "+685", value: "WS" },
  { code: "San Marino", name: "+378", value: "SM" },
  { code: "Sao Tome and Principe", name: "+239", value: "ST" },
  { code: "Saudi Arabia", name: "+966", value: "SA" },
  { code: "Senegal", name: "+221", value: "SN" },
  { code: "Serbia", name: "+381", value: "RS" },
  { code: "Serbia and Montenegro", name: "+381", value: "YU" },
  { code: "Seychelles", name: "+248", value: "SC" },
  { code: "Sierra Leone", name: "+232", value: "SL" },
  { code: "Singapore", name: "+65", value: "SG" },
  { code: "Slovakia", name: "+421", value: "SK" },
  { code: "Slovenia", name: "+386", value: "SI" },
  { code: "Solomon Islands", name: "+677", value: "SB" },
  { code: "Somalia", name: "+252", value: "SO" },
  { code: "South Africa", name: "+27", value: "ZA" },
  { code: "South Korea", name: "+82", value: "KR" },
  { code: "Spain", name: "+34", value: "ES" },
  { code: "Sri Lanka", name: "+94", value: "LK" },
  { code: "Suriname", name: "+597", value: "SR" },
  { code: "Swaziland", name: "+268", value: "SZ" },
  { code: "Sweden", name: "+46", value: "SE" },
  { code: "Switzerland", name: "+41", value: "CH" },
  { code: "Taiwan", name: "+886", value: "TW" },
  { code: "Tajikistan", name: "+992", value: "TJ" },
  { code: "Tanzania, United Republic of", name: "+255", value: "TZ" },
  { code: "Thailand", name: "+66", value: "TH" },
  { code: "Timor-Leste", name: "+670", value: "TL" },
  { code: "Togo", name: "+228", value: "TG" },
  { code: "Tokelau", name: "+690", value: "TK" },
  { code: "Tonga", name: "+676", value: "TO" },
  { code: "Trinidad and Tobago", name: "+1-868", value: "TT" },
  { code: "Tunisia", name: "+216", value: "TN" },
  { code: "Turkey", name: "+90", value: "TR" },
  { code: "Turkmenistan", name: "+993", value: "TM" },
  { code: "Turks and Caicos Islands", name: "+1-649", value: "TC" },
  { code: "Tuvalu", name: "+688", value: "TV" },
  { code: "Uganda", name: "+256", value: "UG" },
  { code: "Ukraine", name: "+380", value: "UA" },
  { code: "United Arab Emirates", name: "+971", value: "AE" },
  { code: "United Kingdom", name: "+44", value: "GB" },
  { code: "United States Minor Outlying Islands", name: "+1", value: "UM" },
  { code: "United States of America", name: "+1", value: "US" },
  { code: "Uruguay", name: "+598", value: "UY" },
  { code: "Uzbekistan", name: "+998", value: "UZ" },
  { code: "Vanuatu", name: "+678", value: "VU" },
  { code: "Venezuela", name: "+58", value: "VE" },
  { code: "Viet Nam", name: "+84", value: "VN" },
  { code: "Virgin Islands (British)", name: "+1-284", value: "VG" },
  { code: "Virgin Islands (U.S.)", name: "+1-340", value: "VI" },
  { code: "Wallis and Futuna", name: "+681", value: "WF" },
  { code: "Yemen", name: "+967", value: "YE" },
  { code: "Zambia", name: "+260", value: "ZM" },
  { code: "Zimbabwe", name: "+263", value: "ZW" }
];
